parameters:
- name: thingsArray
  type: object
  default:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  
trigger:
- main
- Release

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

- task: PowerShell@2
  displayName: 'Build Connectors'
  inputs:
    targetType: 'inline'
    script: |
        cd .\Connectors
        .\build.ps1 $(buildConfiguration)

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployExtension=false /p:AppInsightsInstrumentationKey=$(AppInsightsInstrumentationKey) /nowarn:VSTHRD010'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'Install nuget packages'
  inputs:
    command: 'custom'
    arguments: 'install .\Tests\SpecFlowPackages\Packages.config'

- ${{each thing in parameters.thingsArray}}:
  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests ${{thing}}
    inputs:
      command: test
      projects: '**/SpecFlow.VisualStudio.Tests/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-build'
      testRunTitle: Unit Tests ${{thing}}
    condition: succeededOrFailed()
    
# - ${{each thing in parameters.thingsArray}}:
  # - task: DotNetCoreCLI@2
    # displayName: Run SpecFlow Scenarios ${{thing}}
    # inputs:
      # command: test
      # projects: '**/*[Ss]pecs/*.csproj'
      # arguments: '--configuration $(BuildConfiguration) --runtime win-x64'
      # testRunTitle: Deveroom Specs ${{thing}}
      # publishTestResults: true
    # condition: succeededOrFailed()

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-build --collect "Code coverage"'
    testRunTitle: Unit Tests
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: Run SpecFlow Scenarios
  inputs:
    command: test
    projects: '**/*[Ss]pecs/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --runtime win-x64'
    testRunTitle: 'Deveroom Specs'
    publishTestResults: true
  condition: succeededOrFailed()

